"""create tables

Revision ID: 683be09231b9
Revises: 
Create Date: 2023-10-27 21:41:08.387743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '683be09231b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Patients2')
    op.drop_table('Doctors')
    op.drop_table('Doctors2')
    op.drop_table('Patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Patients',
    sa.Column('PatientID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PatientName2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DoctorEmail', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DoctorID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['Doctors.DoctorID'], name='Patients_ibfk_1'),
    sa.PrimaryKeyConstraint('PatientID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Doctors2',
    sa.Column('DoctorID2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DoctorName2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Specialty2', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('DoctorID2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Doctors',
    sa.Column('DoctorID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DoctorName2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DoctorEmail', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Specialty', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('DoctorID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Patients2',
    sa.Column('PatientID2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PatientName2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DoctorID2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DoctorID2'], ['Doctors2.DoctorID2'], name='Patients2_ibfk_1'),
    sa.PrimaryKeyConstraint('PatientID2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
